digitalocean/pydo

client_gen_config.md

The tests currently fail using the latest version of the OpenAPI spec. This is due to the `POST /v2/apps` method documenting `Accpet` and `Content-Type` paramaters. OpenAPI  has language that reads:
> If in is "header" and the name field is "Accept", "Content-Type" or "Authorization", the parameter definition SHALL be ignored.
https://swagger.io/specification/#parameter-object
This PR uses a directive to remove these for client generation. End users of this client are working with Python dicts, not JSON or YAML. So that should not cause any issue.
```
make download-spec
make clean
make generate
make test-mocked
```
Currently that fails with:
```
__________________________________________________ test_create __________________________________________________
tests/mocked/test_app.py:47: in …
```

Add directive removing accept and content-type arguments from the apps.Create method.

---

.github/workflows/python-client-gen.yml

The client generation workflow is currently failing on the step where it writes the `openapi_short_sha` to file. 
```
curl --fail https://api-engineering.nyc3.digitaloceanspaces.com/spec-ci/DigitalOcean-public-59be3f3.v2.yaml -o DigitalOcean-public.v2.yaml
59be3f3 > DO_OPENAPI_COMMIT_SHA.txt
shell: /usr/bin/bash -e {0}
env:
GH_TOKEN: 
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1280k  100 1280k    0     0  1479k      0 --:--:-- --:--:-- --:--:-- 1477k
/home/runner/work/_temp/2d0868b1-9121-4269-927d-3272fccdf644.sh: line 2: 59be3f3: command not found
Error: …
```

Fix 'Update DO_OPENAPI_COMMIT_SHA.txt step'

---

pyproject.toml

We need to create an initial release for the [tagging/releasing] dependencies (e.g. [github-changelog-generator](https://github.com/digitalocean/github-changelog-generator)) to work properly. 
We've merged updates to the generated client since manually publishing `0.1.1` to pypi, so this will serve as the commit we can tag for the initial github release.

bump package version

---

Makefile

Adds a format command after code generation in the make target so the behavior is the same locally and in the workflow.

Format generated code

---

Makefile

Looks like we need a  dependency on the `install` target in addition to installing poetry.
```
FileNotFoundError
[Errno 2] No such file or directory: b'/snap/bin/black'
at /usr/lib/python3.8/os.py:601 in _execvpe
597│         path_list = map(fsencode, path_list)
598│     for dir in path_list:
599│         fullname = path.join(dir, file)
600│         try:
→  601│             exec_func(fullname, *argrest)
602│         except (FileNotFoundError, NotADirectoryError) as e:
603│             last_exc = e
604│         except OSError as e:
605│             last_exc = e
make: *** [Makefile:38: generate] Error 1
```
https://github.com/digitalocean/openapi/actions/runs/3413887146/jobs/5681158401

Add dependency on install target to generate.

---

.github/release.yml
.github/workflows/release.yml
CONTRIBUTING.md
Makefile
scripts/bumpversion.sh
scripts/tag.sh

This adds a release workflow (triggered by pushed tags) to the repo. 
The Makefile has been updated with the necessary make targets for users to run to bump the version of `pydo`. 
The CONTRIBUTING.md file to include information about how to release the project.
Lastly, a `release.yml` has been added to the root of `.github/` with the configuration for auto-generating release notes.

Add release workflow

---

Makefile

pipeline is still failing because the make step "generate-docs" needs to do a poetry install

adding "install" to make generate-docs

---

.github/workflows/python-client-gen.yml
Makefile
poetry.lock
pyproject.toml

Add a check if the branch already exists. if `add and commit step fails`, the next step will fail and prompt user to delete branch and re-run. Hopefully we won't run into this situation often once the pipeline consistently works.
Also, resolves error in github actions "generate-docs" step: 
```
Run make generate-docs
poetry install --no-interaction -E aio
Installing dependencies from lock file
No dependencies to install or update
Installing the current project: pydo (0.1.2)
Generating documentation...
Converting poetry file to requirements.txt...
/bin/sh: 4: sphinx-apidoc: not found
make: *** [Makefile:93: generate-docs] Error 12[7](https://github.com/digitalocean/pydo/actions/runs/3431821144/jobs/5720400506#step:9:8)
```

Add logic to handle if branch already exists

---

.github/workflows/python-client-gen.yml

remove "continue-on-error" on `create-pr` step in pipeline to have a clear failure if unsuccessful

Remove "continue-on-error"

---

.gitignore

The file is created as part of the workflow changes here: https://github.com/digitalocean/pydo/pull/134 It probably doesn't need to be checked in as it is only used for the PR template. 
It is causing PRs to fail as the linter doesn't like that it uses a level two header (`##`) at the top of the file, but it makes sense in the context of how it is used. https://github.com/digitalocean/pydo/pull/137

Add changelist.md to .gitignore

---

README.md
examples/customize_client_settings/add_http_logger.py
examples/customize_client_settings/custom_endpoint.py
examples/customize_client_settings/custom_request_timeout.py
examples/customize_client_settings/custom_user_agent.py
examples/poc_droplets_volumes_sshkeys.py
tests/integration/conftest.py

Our [API documentation](https://docs.digitalocean.com/reference/api/api-reference/#section/Authentication) uses `$DIGITALOCEAN_TOKEN`, so let's do the same, consistently.
Doing `DO_TOKEN=$DIGITALOCEAN_TOKEN ...` doesn't look that nice.
There are a few formatting changes which come from [psf/black](https://github.com/psf/black) as well; I'll add workflow which tests this when I get a few.

Switch completely to `$DIGITALOCEAN_TOKEN`

---

pyproject.toml

Removing sphinx as dependency and keeping it as a dev-dependencies in an effort to shrink package size.

Remove Sphinx as dependency

---

pyproject.toml

This points the documentation link to https://pydo.readthedocs.io/

Update documentation link in pyproject.toml

---

Makefile

Changes this:
```
$ make help
clean-docs                     Delete everything in docs/build/html
clean                          Removes all generated code (except _patch.py files)
dev-dependencies               Install development tooling
docker-python                  Runs a python shell within a docker container
download-spec                  Download Latest DO Spec
generate                       Generates the python client using the latest published spec first.
generate-docs                  readthedocs requires a requirements.txt file, this step converts poetry file to requirements.txt file before re-gen the docs
install                        Install test dependencies
NOTE: Run 'SPEC_FILE=path/to/local/spec make generate' to skip the download and use a local spec file.
```
To this: …

Makefile: include more targets in help output.

---

.github/workflows/python-client-gen.yml

Making the generated PR titles more descriptive will make the changes in release notes more clear.

Change title of generated PR to include Openapi PR name

---

tests/mocked/test_block_storage.py

refers issue #203
Add mocked tests for volume action.
Add tests for volume_actions.get, volume_actions.list, volume_actions.post, volume_actions.post_by_id

Add Mocked Tests: Volume Actions

---

tests/mocked/test_databases.py

Refer Issue : #204
Added mocked tests for  `databases.add`, `databases.add_connection_pool`, `databases.add_user`, `databases.create_cluster`, `databases.create_replica`

added mocked tests for databases - part 1

---

tests/mocked/test_databases.py

Refer Issue : #205
Add tests for `databases.delete`, `databases.delete_connection_pool`, `databases.delete_online_migration`, `databases.delete_user`, `databases.destroy_replica`

added mocked tests for databases - part 2

---

tests/mocked/test_uptime.py

refers issue #213 
Add Mocked Tests: Uptime
add tests for uptime.lists_check , uptime.create_check
In API resources the method name is given by the name checks_list(), but the actual method name is list_checks(), thats a point to be noted and hence I have used the method list_check() while writing the tests, correct me if I am wrong.

Add Mock Test: Uptime 

---

tests/mocked/test_databases.py

Refer Issue : #207
Add tests for `databases.patch_config`, `databases.reset_auth`, `databases.update_cluster_size`, `databases.update_firewall_rules`, `databases.update_maintenance_window`, `databases.online_migration`, `databases.update_region`, `databases.update_sql_mode`
for `databases.promote_replica`, `databases.update_connection_pool`,
`databases.update_major_version` tests were already there.

added mocked tests for databases - part 4

---

.github/workflows/pr.yaml

We specify poetry version 1.6.1 in most places, e.g.: 
https://github.com/digitalocean/pydo/blob/e51dee5dbc8c2887b15b96a797a661fd5c7a86fb/.github/workflows/pr.yaml#L23
https://github.com/digitalocean/pydo/blob/e51dee5dbc8c2887b15b96a797a661fd5c7a86fb/.github/workflows/python-client-gen.yml#L52
But it looks like we missed updating it here. This is what is causing dependabot PRs to fail the test step.
```
The lock file is not compatible with the current version of Poetry.
Upgrade Poetry to be able to read the lock file or, alternatively, regenerate the lock file with the `poetry lock` command.
```
https://github.com/digitalocean/pydo/actions/runs/6500827562/job/17657028618?pr=195

Update poetry version used in CI

---

pyproject.toml
src/pydo/_version.py

We've had a lot of changes since the last release. We're overdue for another one.
```
~/projects/pydo$ make changes
==> Merged PRs since last release
- #254 - @digitalocean-engineering - [bot] Removes outdated database slugs: Re-Generated From digitalocean/openapi@25b90cb
- #253 - @digitalocean-engineering - [bot] apps: Add documentation for registry_credentials and GHCR images: Re-Generated From digitalocean/openapi@f0e997b
- #251 - @digitalocean-engineering - [bot] Add Database Event logs details to DO openapi: Re-Generated From digitalocean/openapi@32be7e9
- #249 - @digitalocean-engineering - [bot] DBAAS-4506: update kafka topic config options: Re-Generated From digitalocean/openapi@13ed326
- #248 - @digitalocean-engineering - [bot] Add ignore_dbs to online migration docs: Re-Generated …
```

Prep v0.2.0 release.

---

README.md

update readme with known projects delete issue.

Update README.md with known projects delete issue

---

pyproject.toml
src/pydo/_version.py

A lot of changes since last release:
- #288 - @digitalocean-engineering - [bot] Add OpenAPI spec for dedicated egress IPs: Re-Generated From digitalocean/openapi@88ef8cf
- #286 - @digitalocean-engineering - [bot] : Re-Generated From digitalocean/openapi@f331844
- #285 - @digitalocean-engineering - [bot] APPS-8711: container termination controls: Re-Generated From digitalocean/openapi@d8d3901
- #284 - @dependabot[bot] - Bump jinja2 from 3.1.3 to 3.1.4
- #283 - @digitalocean-engineering - [bot] APPS-8386: Deprecate tier upgrade/downgrade fields from instance size: Re-Generated From digitalocean/openapi@20b5ea6
- #281 - @dependabot[bot] - Bump idna from 3.4 to 3.7
- #280 - @digitalocean-engineering - [bot] dbaas: metrics_endpoints is readOnly: Re-Generated From digitalocean/openapi@9d76deb
- …

Prep v0.3.0 Release

---

tests/mocked/test_image_actions.py

This PR is adding mocked tests for image_actions.get, image_actions.list, image_actions.post
Related to https://github.com/digitalocean/pydo/issues/211

Add Mocked Tests: Image Actions

---

.github/workflows/python-client-gen.yml

The client generation workflow is failing due to usage of the deprecated `upload-artifact@v2` action.
```
This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
```
https://github.com/digitalocean/pydo/actions/runs/10905133185

Update from deprecated upload-artifact@v2 action.

---

tests/mocked/test_droplets.py

test: list backup policies

---

.readthedocs.yaml

https://github.com/digitalocean/pydo/commit/579f57d38f132685e76a73ce7bfcd2bff958519c got us one step closer, but now I'm seeing additional errors. `requirements.txt` is using  `>= "3.8.0"`  and `< "4.0.0"'` as the Python version constraint, but `.readthedocs.yaml` is using 3.7 for the build environment.
```
Ignoring sphinx-rtd-theme: markers 'python_full_version >= "3.8.0" and python_full_version < "4.0.0"' don't match your environment
```
:crossed_fingers:

readthedocs: Set python version to 3.8 in .readthedocs.yaml

---

tests/mocked/test_droplets.py

Refers to issue #209 
Added tests for `droplets.destroy_with_associated_resources_selective`, `droplets. destroy_with_associated_resources_dangerous`, `droplets. get_destroy_associated_resources_status`, `droplets. destroy_retry_with_associated_resources`, and `droplets.list_neighbors_ids`

Add Mocked Tests: Droplets 

---

CONTRIBUTING.md

Minor updates in documentation.
`make generate` isn't applying the correct changes to update the pydo version in files, and it seems the version update in the files was done manually.

Minor updates in release notes

---

pyproject.toml
src/pydo/_version.py

Changes:
- #417 - @digitalocean-engineering - [bot] Added reserved ipv6 API specs: Re-Generated From digitalocean/openapi@31fb5b2
- #416 - @digitalocean-engineering - [bot] getagent parity with internal api: Re-Generated From digitalocean/openapi@44575ea
- #415 - @digitalocean-engineering - [bot] extend kubernetes cluster model with routing_agent flag: Re-Generated From digitalocean/openapi@5285969
- #413 - @digitalocean-engineering - [bot] Update one click api permissions: Re-Generated From digitalocean/openapi@8495f9e
- #411 - @digitalocean-engineering - [bot] GenAI: Add Anthropic API Key Endpoints: Re-Generated From digitalocean/openapi@25f2388

Prep v0.9.0 release

---

.github/workflows/release.yml

Fixing the release pipeline.
v3.1.1 was deprecated.
https://github.com/digitalocean/pydo/actions/runs/13551071021

Update github upload-artifact to v4

---

pyproject.toml
src/pydo/_version.py

Sorry, it's just to much work to clean up all v0.9.0 artefacts to be able to release with the same tag.
https://github.com/digitalocean/pydo/actions/runs/13551640449/job/37876389228#step:8:23

Prep v0.9.1 release
